name: Docker Image CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  push_to_rigistry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: heyyakash/vox:latest

      - name: SSH 
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name : SSH into digital ocean server
        run : ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_IP }} "docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }} && docker stop vox-backend && docker rm vox-backend && docker rmi heyyakash/vox:latest && docker run -v /root/configs:/app/certs -d -p 5000:5000 --name vox-backend heyyakash/vox:latest"

            
        
