name: Docker Image CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  push_to_rigistry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: heyyakash/vox:latest
